storybookjs/test-runner

README.md
package.json
playwright/custom-environment.js
src/csf/transformCsf.ts
yarn.lock

Going with an environment variable for now

support target url via environment variable

---

package.json

Fix: add missing files to package

---

README.md
bin/test-storybook.js
playwright/custom-environment.js
src/jsdom/transformJsdom.test.ts

<details>
<summary>📦 Published PR as canary version: <code>0.0.1-canary.17.b258153.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.0.1-canary.17.b258153.0
yarn add @storybook/test-runner@0.0.1-canary.17.b258153.0
```
</details>

docs: update README with instructions

---

README.md
playwright/test-runner-jest.config.js
src/setup-page.ts

This PR includes:
#94 Add output limit
#93 Fixup README typo

Release 0.0.7

---

package.json
src/csf/transformCsf.ts
src/playwright/transformPlaywright.test.ts
src/playwright/transformPlaywright.ts
src/playwright/transformPlaywrightJson.test.ts
yarn.lock

This release contains the following contributions:
Support Storybook 6.5 (https://github.com/storybookjs/test-runner/pull/107)

Release 0.1.0

---

.vscode/settings.json
README.md
bin/test-storybook.js
package.json
yarn.lock

[Document issue with Jest on Windows CI #105](https://github.com/storybookjs/test-runner/pull/105)
[Add Jest compatibility check #111](https://github.com/storybookjs/test-runner/pull/111)

Release 0.1.1

---

README.md
bin/test-storybook.js
package.json
src/playwright/transformPlaywrightJson.test.ts
src/playwright/transformPlaywrightJson.ts
src/setup-page.ts
src/util/getCliOptions.test.ts
src/util/getCliOptions.ts
src/util/getParsedCliOptions.ts
yarn.lock

Fetch index.json and refer to "index json" mode [#124](https://github.com/storybookjs/test-runner/pull/124)
Improve code coverage for coverage merging [#130](https://github.com/storybookjs/test-runner/pull/130)
Document need for a custom snapshotResolver [#131](https://github.com/storybookjs/test-runner/pull/131)
fix: support index.html URLs [#139](https://github.com/storybookjs/test-runner/pull/139)
Support watchAll Jest flag [#142](https://github.com/storybookjs/test-runner/pull/142)

Release 0.4.0

---

README.md
bin/test-storybook.js
package.json
yarn.lock

Turn Jest into an internal dependency #175

Release 0.6.2

---

src/playwright/transformPlaywright.test.ts
src/playwright/transformPlaywright.ts
src/playwright/transformPlaywrightJson.test.ts
src/setup-page.ts

Support storyStoreV7 in coverage check #177

Release 0.6.3

---

package.json
yarn.lock

Self-merging @yannbf @tmeasday 
<details>
<summary>📦 Published PR as canary version: <code>0.9.1--canary.212.769fef8.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.9.1--canary.212.769fef8.0
yarn add @storybook/test-runner@0.9.1--canary.212.769fef8.0
```
</details>

Upgrade CSF to next

---

.github/workflows/nightly.yml

Upgrade nightly to next instead of future

---

src/setup-page.ts

<details>
<summary>📦 Published PR as canary version: <code>0.9.2--canary.234.da8ba2d.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.9.2--canary.234.da8ba2d.0
yarn add @storybook/test-runner@0.9.2--canary.234.da8ba2d.0
```
</details>

Fix target url in error feedback

---

package.json
yarn.lock

🎉
<details>
<summary>📦 Published PR as canary version: <code>0.9.5--canary.288.1b073f4.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.9.5--canary.288.1b073f4.0
yarn add @storybook/test-runner@0.9.5--canary.288.1b073f4.0
```
</details>

Bump @storybook/csf to 0.1.0

---

package.json
src/test-storybook.ts
yarn.lock

<details>
<summary>📦 Published PR as canary version: <code>0.10.1--canary.299.3458403.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.10.1--canary.299.3458403.0
yarn add @storybook/test-runner@0.10.1--canary.299.3458403.0
```
</details>

Upgrade glob to v10

---

playwright/test-runner-jest.config.js

For a better autocomplete experience!
<details>
<summary>📦 Published PR as canary version: <code>0.10.1--canary.297.d3b6668.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.10.1--canary.297.d3b6668.0
yarn add @storybook/test-runner@0.10.1--canary.297.d3b6668.0
```
</details>

Improve ejected config types

---

README.md

Corrected because the content of this comment was not reflected in other parts of the usage.
https://github.com/storybookjs/test-runner/pull/257#discussion_r1230432222

docs: fix github actions example for shard usage

---

README.md
src/test-storybook.ts

Introduced by mistake from another PR.

Fix: Do not set test root outside index json mode

---

README.md
src/playwright/hooks.ts

<details>
<summary>📦 Published PR as canary version: <code>0.15.2--canary.393.bc4821e.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.15.2--canary.393.bc4821e.0
yarn add @storybook/test-runner@0.15.2--canary.393.bc4821e.0
```
</details>

Docs: Update tags documentation

---

MIGRATION.portable-stories.md
MIGRATION.test-runner.md

With this small pull request the migration documentation was updated to include a feedback form to help users interface with us and provide useful information to help shape the tooling.
@yannbf when you have a moment. Can you check this and see if you're ok with it? Thanks in advance.

Docs: Adds feedback form to migration documentation

---

src/csf/transformCsf.ts
src/playwright/transformPlaywrightJson.ts

<details>
<summary>📦 Published PR as canary version: <code>0.16.1--canary.425.19c0662.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.16.1--canary.425.19c0662.0
yarn add @storybook/test-runner@0.16.1--canary.425.19c0662.0
```
</details>

Fix build step

---

src/setup-page-script.ts

<details>
<summary>📦 Published PR as canary version: <code>0.16.1--canary.421.8fdba11.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.16.1--canary.421.8fdba11.0
yarn add @storybook/test-runner@0.16.1--canary.421.8fdba11.0
```
</details>

Support unhandled rendering errors

---

package.json
src/test-storybook.ts
yarn.lock

Closes #451
This PR enables the test-runner to run standalone, even in non-storybook directories with a single command, for instance:
```sh
npx @storybook/test-runner --url https://mealdrop.vercel.app/storybook
```
<details>
</details>
<details>
<summary>📦 Published PR as canary version: <code>0.18.1--canary.464.5ad382f.0</code></summary>
<br />
```bash
npm install …
```

Fix: Skip requiring a main.js file in index.json mode

---

src/playwright/hooks.ts

Closes #436
<details>
</details>
<details>
<summary>📦 Published PR as canary version: <code>0.18.1--canary.462.54e66ce.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.18.1--canary.462.54e66ce.0
yarn add @storybook/test-runner@0.18.1--canary.462.54e66ce.0
```
</details>

Fix getStoryContext type

---

package.json
yarn.lock

https://github.com/swc-project/swc/issues/8988
<details>
<summary>📦 Published PR as canary version: <code>0.18.2--canary.474.9bf1a01.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.18.2--canary.474.9bf1a01.0
yarn add @storybook/test-runner@0.18.2--canary.474.9bf1a01.0
```
</details>

Pin `@swc/core` to 1.5.7

---

src/csf/__snapshots__/transformCsf.test.ts.snap
src/playwright/transformPlaywright.test.ts
src/playwright/transformPlaywright.ts
src/playwright/transformPlaywrightJson.test.ts

Fix postVisit hook issue

---

README.md

Closes #522
Given alerts Markdown for Note section.
_N/A._
<details>
</details>

style(README): highlight Markdown Note section

---

src/setup-page-script.ts

Fix a11y compatibility with Storybook 8.5 and above

---

README.md
src/setup-page-script.ts

Promote v0.21.1-next.0

---

src/setup-page-script.ts

Revert "Fix a11y compatibility with Storybook 8.5 and above"

---

src/setup-page-script.ts

Release 0.21.2 patch

---

src/setup-page-script.ts
src/setup-page.ts

Release 0.21.3

---

src/setup-page-script.ts

Fix: Support a11y disable parameter

---

README.md
src/test-storybook.ts
src/util/getCliOptions.ts
src/util/getParsedCliOptions.ts
src/util/getStorybookMetadata.ts

Add telemetry to test run
