storybookjs/test-runner

- playwright/custom-environment.js
- playwright/transform.js
Now the failures provide a helpful message with a link to the story:
> feat: improve error messages with custom error

- playwright/custom-environment.js
If the user passes incorrect urls for TARGET_URL and REFERENCE_URL like: sb.com (without protocol) and sb.com/iframe.html, the lib will sanitize it.
In addition to that, I added a `waitForSelector` command that waits for 10 seconds to get the #root element from Storybook, if it fails, it will output this (disregard the 60 seconds, I changed to 10):
> Sanitize target and reference urls and wait for Storybook selector before running test

- README.md
- playwright/custom-environment.js
In order to avoid users getting into frustrating situations like running test-runner against a private Storybook, I updated the docs and the feedback message when it times out in situations like that.
<details>
<summary>📦 Published PR as canary version: <code>0.0.2-canary.27.eabf5e0.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.0.2-canary.27.eabf5e0.0
yarn add @storybook/test-runner@0.0.2-canary.27.eabf5e0.0
```
</details>
> Update ci recipes and timeout feedback

- README.md
Issue: #21 
<details>
<summary>📦 Published PR as canary version: <code>0.0.2-canary.29.aa0a460.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.0.2-canary.29.aa0a460.0
yarn add @storybook/test-runner@0.0.2-canary.29.aa0a460.0
```
</details>
closes #21
> docs(README): add section about jest

- .storybook/main.js
- playwright/transform.js
- src/csf/transformCsf.ts
- src/playwright/index.ts
- src/playwright/transformPlaywright.test.ts
- src/playwright/transformPlaywright.ts
- stories/basic/Button.stories.js
Issue: #19 
<details>
<summary>📦 Published PR as canary version: <code>0.0.2-canary.35.8a26a58.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.0.2-canary.35.8a26a58.0
yarn add @storybook/test-runner@0.0.2-canary.35.8a26a58.0
```
</details>
> Support auto title stories

- .github/workflows/test.yml
- bin/test-storybook.js
- package.json
- playwright/custom-environment.js
- src/csf/transformCsf.ts
- src/jsdom/transformJsdom.ts
- src/playwright/transformPlaywright.test.ts
- src/playwright/transformPlaywright.ts
- src/playwright/transformPlaywrightJson.test.ts
- src/playwright/transformPlaywrightJson.ts
- Removed the checks for hasPlayFn in the codebase
- Made the error link always include addon interactions
- Added stories-json test to CI
<details>
<summary>📦 Published PR as canary version: <code>0.0.2-canary.37.86a700a.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.0.2-canary.37.86a700a.0
yarn add @storybook/test-runner@0.0.2-canary.37.86a700a.0
```
</details>
> Cleanup play function checks

- README.md
- bin/test-storybook.js
- package.json
- src/playwright/transformPlaywright.test.ts
- src/playwright/transformPlaywright.ts
- src/util/cli.test.ts
- src/util/cli.ts
- src/util/helpers.ts
- yarn.lock
Issue: SB-20 
This PR adds a CLI wrapper with the following commands:
It will retain test runner configs and pass the rest to jest-playwright. If users end up trying a flag that is not supported, they will get an error message with a link to open an issue on this repo:
<details>
<summary>📦 Published PR as canary version: <code>0.0.2-canary.41.9b77c29.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.0.2-canary.41.9b77c29.0
yarn add @storybook/test-runner@0.0.2-canary.41.9b77c29.0
```
</details>
> Add CLI wrapper

- bin/test-storybook.js
From @kylegach's feedback, now the error message is more helpful, providing a solution to use TARGET_URL but also a link to the docs in case users need a bit more context
> fix: improve error message in start-storybook

- README.md
- src/util/getParsedCliOptions.ts
In case people are using test hooks for snapshot testing, it's important to expose this jest flag to update the snapshots without having to go into watch mode
<details>
<summary>📦 Published PR as canary version: <code>0.0.3-canary.52.ec4fcc0.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.0.3-canary.52.ec4fcc0.0
yarn add @storybook/test-runner@0.0.3-canary.52.ec4fcc0.0
```
</details>
> feat: add update snapshot command to cli

- README.md
- bin/test-storybook.js
- src/util/getCliOptions.ts
- src/util/getParsedCliOptions.ts
- test-runner-jest.config.js
Issue: #42 
Running eject for the first time:
And in case the config file already exists, it will notify the user (but still override it without prompting)
- Using the test-runner in monorepos. Very likely the logic to detect and use the config file is not ready for that
- Adding inquirer or any other library to allow for prompting user to things like (are you sure you want to override ; we detected an external storybook url, do you want to use stories-json flag)
<details>
<summary>📦 Published PR as canary version: <code>0.0.3-canary.54.04b73e7.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.0.3-canary.54.04b73e7.0
yarn add @storybook/test-runner@0.0.3-canary.54.04b73e7.0
```
</details>
> feat: add eject command

- bin/test-storybook.js
> fix: add  file location to eject error message

- README.md
- bin/test-storybook.js
- src/config/jest-playwright.ts
- src/util/getCliOptions.test.ts
- src/util/getCliOptions.ts
- src/util/getParsedCliOptions.ts
This adds the possibility to set browsers via CLI such as:
```
yarn test-storybook --browsers webkit firefox
```
<details>
<summary>📦 Published PR as canary version: <code>0.0.3-canary.55.c9e2fe2.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.0.3-canary.55.c9e2fe2.0
yarn add @storybook/test-runner@0.0.3-canary.55.c9e2fe2.0
```
</details>
> feat: add browsers flag

- README.md
- bin/test-storybook.js
- playwright/custom-environment.js
- src/util/getCliOptions.ts
- src/util/getParsedCliOptions.ts
This PR adds a new way to set target url by using `--url` instead of `process.env.TARGET_URL`.
If the user does use TARGET_URL, it will be taken as precedence so it supports both.
<details>
<summary>📦 Published PR as canary version: <code>0.0.3-canary.56.6df6b2d.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.0.3-canary.56.6df6b2d.0
yarn add @storybook/test-runner@0.0.3-canary.56.6df6b2d.0
```
</details>
> feat: add url flag

- README.md
- bin/test-storybook.js
- package.json
- src/util/getParsedCliOptions.ts
- yarn.lock
Now the test-runner will auto-detect if the Storybook is being served locally or remotely, then use --stories-json mode by default, but also allowing to override it both to force it being used in case `--stories-json` is passed, or to force not to use it with `--no-stories-json`
> feat: auto detect stories json mode

- package.json
- src/config/jest-playwright.ts
- yarn.lock
For a much better UX:
<details>
<summary>📦 Published PR as canary version: <code>0.0.3-canary.61.4c21f55.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.0.3-canary.61.4c21f55.0
yarn add @storybook/test-runner@0.0.3-canary.61.4c21f55.0
```
</details>
> feat: add typeahead jest plugin

- src/playwright/transformPlaywright.test.ts
- src/playwright/transformPlaywright.ts
- test-runner-jest.config.js
<details>
<summary>📦 Published PR as canary version: <code>0.0.4-canary.65.73bc8bf.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.0.4-canary.65.73bc8bf.0
yarn add @storybook/test-runner@0.0.4-canary.65.73bc8bf.0
```
</details>
> fix: use correct import in generated test

- .storybook/test-runner.ts
- src/setup-page.ts
Run a storybook that supports `stories.json` e.g. from the monorepo
Then run snapshot tests against it, e.g.
```
VIEW_MODE=docs yarn test-storybook:no-cache --url http://localhost:9006 --stories-json
```
> Add ability to test docs pages via VIEW_MODE env var

- src/setup-page.ts
The  "page loaded in Xms" were adding noise to the reports:
<details>
<summary>📦 Published PR as canary version: <code>0.0.5-canary.86.11580c1.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.0.5-canary.86.11580c1.0
yarn add @storybook/test-runner@0.0.5-canary.86.11580c1.0
```
</details>
> cleanup page opened log

- bin/test-storybook.js
- src/util/getStorybookMetadata.test.ts
- src/util/getStorybookMetadata.ts
We want to look into actually working around this problem, but in the meantime, hopefully this will point folks in the right direction.
<details>
<summary>📦 Published PR as canary version: <code>0.0.6-canary.90.afeeaef.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.0.6-canary.90.afeeaef.0
yarn add @storybook/test-runner@0.0.6-canary.90.afeeaef.0
```
</details>
> Log a warning if you try and run against a lazy-compiled storybook

- README.md
- playwright/test-runner-jest.config.js
- src/setup-page.ts
By default, the test runner will truncate error output at 1000 characters, and you can check the full output directly in Storybook, in the browser. If you do want to change that limit, however, you can do so by setting the `DEBUG_PRINT_LIMIT` environment variable to a number of your choosing, for example, `DEBUG_PRINT_LIMIT=5000 yarn test-storybook`.
Debatable:
1 - Default limit. Currently 1000
2 - Env var name. Currently the same as the one used by testing library, `DEBUG_PRINT_LIMIT`
<details>
<summary>📦 Published PR as canary version: <code>0.0.7-canary.94.a4889a0.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.0.7-canary.94.a4889a0.0
yarn add @storybook/test-runner@0.0.7-canary.94.a4889a0.0
```
</details>
> Add output limit

- package.json
Currently jest is automatically updated to v28, but this leads to an error:
>TypeError: Jest: Got error running globalSetup - /home/bodo/my-project/node_modules/@storybook/test-runner/playwright/global-setup.js, reason: Class extends value #<Object> is not a constructor or null
So we should limit the version for now.
> Limit jest to version 26 or 27

- README.md
I was scratching my head for a bit as to why I was getting an error that no tests were found, when I had a `.stories.mdx` file that I assumed would be picked up.  According to https://github.com/storybookjs/test-runner/issues/36, `--stories-json` mode should be used to enable running tests against such stories.
This adds a brief note in the README about this, though it might be good to clearly document exactly which tests this _does_ support out of the box, and point to stories.json mode for others.  But, I'll admit that I'm not clear on exactly what is supported myself.
<details>
<summary>📦 Published PR as canary version: <code>0.0.8-canary.102.5ccece6.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.0.8-canary.102.5ccece6.0 …
```
> Document limitation for .mdx stories

- package.json
- yarn.lock
I had a test failure begin in https://github.com/storybookjs/builder-vite/pull/357 when updating the test-runner to anything higher than 0.0.5-next.0.  I traced it down to the test-runner installing and using a 6.4 version of @storybook/store, while my storybook project is on 6.5.0-beta.0.
I think this change is the correct way to handle this, by moving the storybook projects to peerDependencies, with a range that includes 6.5.0 pre-releases.  Any other approach risks installing a different version for the test runner than what is installed in the main project.
<details>
<summary>📦 Published PR as canary version: <code>0.0.8-canary.101.df0a2dc.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.0.8-canary.101.df0a2dc.0
yarn add …
```
> Move storybook packages to peer deps

- README.md
- package.json
- yarn.lock
This release contains:
#98 Limit jest to version 26 or 27
#101 Move storybook packages to peer deps
#102 Document limitation for .mdx and .svelte stories
> Release 0.0.8

- package.json
- src/csf/transformCsf.ts
- src/playwright/transformPlaywright.test.ts
- src/playwright/transformPlaywright.ts
- src/playwright/transformPlaywrightJson.test.ts
- src/playwright/transformPlaywrightJson.ts
- yarn.lock
[BREAKING CHANGES]: Drop Storybook 6.4 support
fixes #106
<details>
<summary>📦 Published PR as canary version: <code>0.0.9--canary.107.1f96eca.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.0.9--canary.107.1f96eca.0
yarn add @storybook/test-runner@0.0.9--canary.107.1f96eca.0
```
</details>
This version adds support to Storybook 6.5 and drops support for Storybook 6.4. Unfortunately there was a breaking change in an internal API from `@storybook/store` which is used by the test runner, which **only affects users that use the auto title feature**. 
Changes included from [this pull request](https://github.com/storybookjs/test-runner/pull/107) (#107)
> fix: Support Storybook 6.5

- README.md
An attempt to document what we found debugging this issue here: https://github.com/storybookjs/builder-vite/pull/358
> Document issue with Jest on Windows CI

- .vscode/settings.json
- README.md
- bin/test-storybook.js
- package.json
- yarn.lock
Unfortunately the test runner is not compatible with Jest 28 and will not be until https://github.com/playwright-community/jest-playwright/issues/796 is resolved. 
This PR adds a check to warn and prevent users from running into compatibility issues
> Add Jest compatibility check

- .github/workflows/nightly.yml
- .storybook/main.js
This PR introduces a reporting mechanism that will run nightly so we are notified whenever the test runner breaks with pre-releases of Storybook.
> Add reporting to CI

- README.md
With this pull request, the Readme is updated to lock Jest to version 27.5.1 to prevent issues with the latest release
> Updates readme to lock Jest to version 27

- package.json
- yarn.lock
The new version 1.7.1 has limited the version range for jest to <28.
Cf. https://github.com/playwright-community/jest-playwright/issues/793
> chore(DEPS): update jest-playwright-preset

- .storybook/test-runner.ts
- README.md
- src/playwright/hooks.ts
- src/setup-page.ts
- src/util/getStorybookMetadata.test.ts
- stories/atoms/Button.stories.js
Issue #97 
**getStoryContext utility [#125](https://github.com/storybookjs/test-runner/pull/125)**
While running tests using the hooks, you might want to get information from a story, such as the parameters passed to it, or its args. The test runner now provides a `getStoryContext` utility function that fetches the story context for the current story:
```js
await getStoryContext(page, context);
```
You can use it for multiple use cases, and here's an example that combines the story context and accessibility testing:
```js
// .storybook/test-runner.js
const { getStoryContext } = require('@storybook/test-runner');
const { injectAxe, checkA11y } = require('axe-playwright');
module.exports = {
async preRender(page, context) {
await injectAxe(page);
},
async postRender(page, context) {
// Get …
```
> feat: provide global getStoryContext utility

- README.md
I noticed that (DOM) snapshots get stored alongside with the generated tests, and since they get generated in a temporary folder, that doesn't work.
Fortunately Jest supports a custom `snapshotResolver`, so I updated the README with instructions on how to use that.
> Document need for a custom snapshotResolver

- README.md
- bin/test-storybook.js
- src/util/getParsedCliOptions.ts
See https://jestjs.io/docs/cli#--watchall
In some occasions, for example in a non-git directory, `--watch` won't work, and the suggested workaround is to use `--watchAll`.
> Support watchAll Jest flag

- src/setup-page.ts
Issue: #155 
For now, the feature is always enabled. It only provides the logs when there are failures.
Here's a code example:
```js
export const Logs = (args) => {
console.log("here's an object", { hello: "world" })
console.warn("The API is deprecated!")
console.error("Some error happened.")
return (
<button type="button" onClick={() => args.onSubmit('clicked')}>
Click
</button>
)
};
Logs.play = async ({ args, canvasElement }) => {
console.log("log from play function")
await userEvent.click(within(canvasElement).getByRole('buttons')); // <-- will fail
await expect(args.onSubmit).toHaveBeenCalledWith(expect.stringMatching(/([A-Z])\w+/gi));
};
```
And here's the output:
Here's how it looks like on a more realistic scenario:
<details>
<summary>📦 Published PR as canary version: …
> feat: add console logs on test failure

- src/setup-page.ts
The test runner now throws an error when running `yarn test-storybook --coverage` and the coverage is not correctly set up. This could mean that an user might be running `--coverage` without instrumenting their code with istanbul, which would lead to problems!
> feat: throw error on unconfigured coverage when running with --coverage

- src/util/getParsedCliOptions.ts
Issue: #163 
Thank you so much for flagging this @stijnkoopal !!
The `--watch` flag was previously not working, and now it's fixed.
> fix --watch cli option

- .storybook/test-runner.ts
- README.md
- src/setup-page.ts
In Storybook 7.0, the root selector changed from #root to #storybook-root. Both selectors are now supported in the internals of the test runner
> support Storybook 7.0 root selector

- README.md
- bin/test-storybook.js
- package.json
- yarn.lock
The Storybook test runner will now contain Jest as an internal dependency, which means that if you installed Jest just for the purpose of using the Storybook test runner, you can now remove it!
<details>
<summary>📦 Published PR as canary version: <code>0.6.2--canary.175.18eec92.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.6.2--canary.175.18eec92.0
yarn add @storybook/test-runner@0.6.2--canary.175.18eec92.0
```
</details>
> feat: turn Jest into an internal dependency

- src/playwright/transformPlaywright.test.ts
- src/playwright/transformPlaywright.ts
- src/playwright/transformPlaywrightJson.test.ts
- src/setup-page.ts
This release fixes an issue where the coverage check was not working for projects using storyStoreV7.
<details>
<summary>📦 Published PR as canary version: <code>0.6.3--canary.177.1385c6d.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.6.3--canary.177.1385c6d.0
yarn add @storybook/test-runner@0.6.3--canary.177.1385c6d.0
```
</details>
> Support storyStoreV7 in coverage check

- README.md
As mentioned in #148, best course of action for now is to add documentation explaining what could be the cause of that issue and how to circumvent it.
> Add remark regarding different coverage providers

- .gitignore
- README.md
- bin/test-storybook.js
- package.json
- src/config/jest-playwright.ts
- src/util/getCliOptions.ts
- src/util/getParsedCliOptions.ts
- yarn.lock
The test runner now supports JUnit XML test reports out of the box with a `--junit` flag:
```sh
yarn test-storybook --junit
```
With that flag, the test runner will add `jest-junit` to the reporters list and generate a test report in a JUnit XML format. You can further configure the behavior of `jest-junit` by either setting specific `JEST_JUNIT_*` environment variables or by defining a `jest-junit` field in your package.json with the options you want, which will be respected when generating the report. You can look at all available options here: https://github.com/jest-community/jest-junit#configuration
<details>
<summary>📦 Published PR as canary version: <code>0.6.4--canary.179.342c799.0</code></summary>
<br />
```bash
npm install …
```
> add --junit flag to test runner

- .gitignore
- README.md
- bin/test-storybook.js
- package.json
- src/config/jest-playwright.ts
- src/util/getCliOptions.ts
- src/util/getParsedCliOptions.ts
- yarn.lock
add junit flag to test runner #179 
Published prerelease version: `v0.6.4-next.0`
<details>
<summary>Changelog</summary>
The test runner now supports JUnit XML test reports out of the box with a `--junit` flag:
```sh
yarn test-storybook --junit
```
With that flag, the test runner will add `jest-junit` to the reporters list and generate a test report in a JUnit XML format. You can further configure the behavior of `jest-junit` by either setting specific `JEST_JUNIT_*` environment variables or by defining a `jest-junit` field in your package.json with the options you want, which will be respected when generating the report. You can look at all available options here: https://github.com/jest-community/jest-junit#configuration
---
- add --junit flag to test runner …
> Release 0.6.4

- package.json
- yarn.lock
I'm doing an experiment to remove some unused dependencies from core Storybook packages, and found that some of the Vite sandboxes started to fail when the test-runner was run, due to missing `@babel/` dependencies.  Then I noticed that test-runner doesn't actually depend on them correctly.  It's using babel to perform transforms, so I think it should include them in `dependencies` not `devDependencies`.  
I also ran `npx depcheck` and located a few other deps that the test-runner is relying on, but isn't specifying directly, so I added those as well.
> Add missing dependencies

- README.md
Added code example in Readme of Global utility functions. 
The reason is that when a11y rule is configured on story level, the rules are applied in the local Storybook instance but when run test-storybook in command line, those rules are ignored and throws violations i.  e.g.) Disabling some rules using rule ID.  
Because of that, we need to configure configureAxe() and before a11y test runs. 
I added the example since there is no documentation for the configuration, and I belive there would be a common configuration case if developers override a11y rules on story base.
This is the discussion about the case. https://discord.com/channels/486522875931656193/580149748225409024/1007635983707156571
> docs(README): Update a11y recipe

- README.md
- package.json
- yarn.lock
Update a11y recipe in README #186
Add missing dependencies #187
> Release 0.7.1

- yarn.lock
@yannbf I investigated with @ndelangen and we think that the nightly build has been failing due to a bad lockfile with multiple versions of various storybook packages stepping on one another. We verified this to a degree on my dev machine. This PR regens the lockfile (which does not affect test-runner users) and hopefully the CI will pass (or fail in the same way as earlier) with this change.
> Regenerate yarn.lock [skip ci]

- src/setup-page.ts
When running `yarn test-storybook` on my story, a 3rd party library throws an uncaught exception, but `StorybookTestRunnerError` _assumes_ `logs` is an array, which throws this error:
```console
UnhandledPromiseRejectionWarning: page.evaluate: TypeError: Cannot read properties of undefined (reading 'length')
at new StorybookTestRunnerError (<anonymous>:58:34)
at __throwError (<anonymous>:71:15)
at eval (eval at evaluate (:192:30), <anonymous>:4:19)
at UtilityScript.evaluate (<anonymous>:194:17)
at UtilityScript.<anonymous> (<anonymous>:1:44)
```
This PR simply **defaults `logs` to `[]`**, so I can correctly see that the underlying error is _actually_ coming from a 3rd party library:
```console
Cannot read properties of null (reading 'focus')
```
> Fix StorybookTestRunnerError – length on undefined

- .storybook/is-test-runner.js
- .storybook/preview.js
- README.md
- bin/test-storybook.js
- package.json
- src/setup-page.ts
- stories/atoms/Button.stories.js
#194 Fix StorybookTestRunnerError – length on undefined
#198 Add isTestRunner utility
> Release 0.8.0

- bin/test-storybook.js
I was getting an error when running the test-runner, but it did not fail CI because an exit code of `0` was being returned.  Also, the error message did not have any stack trace or other information, so it was nearly impossible to tell why it was failing.
This PR adds a stacktrace to the error message returned, and ensures that we exit with a non-zero code, so that CI fails correctly.  I also made the title red, just because I think it helps a little for clarity.
Before: 
After: 
Underlying issue causing this error: https://github.com/storybookjs/test-runner/issues/200
Oh, and I fixed some import paths.  I think the actual imports were working before, but typescript couldn't find them, I guess due to the way that the compiled babel output converted `export * from`.
> Improve error logging and ensure non-zero exit

- .github/workflows/nightly.yml
Make sure that the exit code from `test-storybook:ci-failures` is inverted
> Fix nightly check for failures

- package.json
- yarn.lock
Attempt to fix a sandbox issue in the SB monorepo
<details>
<summary>📦 Published PR as canary version: <code>0.8.1--canary.202.99d82aa.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.8.1--canary.202.99d82aa.0
yarn add @storybook/test-runner@0.8.1--canary.202.99d82aa.0
```
</details>
> Upgrade preset-env to latest

- README.md
- src/util/getParsedCliOptions.ts
Issue: #159 
Adds an option `--ci` that passes it to Jest to run it in CI mode so that the test fails if new snapshots are introduced that have not been committed yet.
```
yarn test-storybook --ci
```
> feat: add cli option --ci

- README.md
Issue: #220
So users can prefix their file names
> Docs: add recipe for browser name

- package.json
- playwright/jest-setup.js
- src/csf/transformCsf.ts
- src/playwright/hooks.ts
- src/playwright/transformPlaywright.test.ts
- src/playwright/transformPlaywright.ts
- src/playwright/transformPlaywrightJson.test.ts
- src/typings.d.ts
Issue: #136
This PR removes usage of `global` package and uses `globalThis` instead, which makes the retrying mechanism of the test-runner work in index.json (or stories.json) mode.
Additionally, it provides a log message to warn users that the story of which needs a retry, probably has done a navigation.
> Make setup-page globally available for index.json mode compatibility

- README.md
- src/util/getParsedCliOptions.ts
Picking from pull request #243 from `Niznikr/feat/shard-cli`
<details>
<summary>📦 Published PR as canary version: <code>0.9.3--canary.246.9fd8f6a.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.9.3--canary.246.9fd8f6a.0
yarn add @storybook/test-runner@0.9.3--canary.246.9fd8f6a.0
```
</details>
> feat: add shard cli option

- README.md
- bin/test-storybook.js
- package.json
- yarn.lock
Fixes #228 #91
The test runner will now support whatever extension you define for your `storybook-test-runner.config.*` file.
Additionally, it will look for that file under a custom config dir if passed with `--config-dir`.
Closes #248 #231 
<details>
<summary>📦 Published PR as canary version: <code>0.9.4--canary.259.2b62dd1.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.9.4--canary.259.2b62dd1.0
yarn add @storybook/test-runner@0.9.4--canary.259.2b62dd1.0
```
</details>
> Support other test-runner config extensions

- README.md
- bin/test-storybook.js
- package.json
- src/setup-page.ts
- src/util/getParsedCliOptions.ts
- yarn.lock
This PR includes the following contributions:
[Use ipv4 loopback address #252](https://github.com/storybookjs/test-runner/pull/252)
[Fix safe json stringify code #239](https://github.com/storybookjs/test-runner/pull/239)
[Support other test-runner config extensions #259](https://github.com/storybookjs/test-runner/pull/259)
<details>
<summary>📦 Published PR as canary version: <code>0.9.4--canary.258.06d5faf.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.9.4--canary.258.06d5faf.0
yarn add @storybook/test-runner@0.9.4--canary.258.06d5faf.0
```
</details>
> Release 0.9.4

- README.md
This PR updates the Readme to also mention that `index.json` mode is useful for testing stories not written as plain CSF stories.
This was prompted by https://github.com/storybookjs/test-runner/issues/262.
> Document index.json mode for Svelte CSF

- package.json
- src/playwright/transformPlaywright.ts
- yarn.lock
And fix related deprecation messages
Is this a patch release @yannbf?
<details>
<summary>📦 Published PR as canary version: <code>0.9.5--canary.273.08bdc9c.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.9.5--canary.273.08bdc9c.0
yarn add @storybook/test-runner@0.9.5--canary.273.08bdc9c.0
```
</details>
> Use preview api instead of store 

- src/util/__snapshots__/getStorybookMain.test.ts.snap
- src/util/getStorybookMain.test.ts
- src/util/getStorybookMain.ts
Closes https://github.com/storybookjs/test-runner/issues/277
Updated getStorybookMain to throw an error if stories are not found in main.js
<details>
<summary>📦 Published PR as canary version: <code>0.9.5--canary.278.4ef4cb1.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.9.5--canary.278.4ef4cb1.0
yarn add @storybook/test-runner@0.9.5--canary.278.4ef4cb1.0
```
</details>
> Update getStorybookMain to throw an error if stories are not found in main.js

- src/test-storybook.ts
> fix(test-storybook): Fix test-runner-jest.config.js file not being found in STORYBOOK_CONFIG_DIR on Windows

- playwright/custom-environment.js
There was one line of code still referencing regenerator-runtime. It's no longer used.
Fixes: #304
<details>
<summary>📦 Published PR as canary version: <code>0.10.1--canary.303.86f873e.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.10.1--canary.303.86f873e.0
yarn add @storybook/test-runner@0.10.1--canary.303.86f873e.0
```
</details>
> fix: Remove last reference to regenerator-runtime

- src/util/getCliOptions.test.ts
- src/util/getCliOptions.ts
**Describe the bug**
When you try to run `npx test-storybook TestName` in order to run tests on a specific file - you get the following error:
```
TypeError: rawArgv2.replace is not a function
at <anonymous> (node_modules/@storybook/test-runner/node_modules/jest-cli/build/cli/index.js:188:40)
at Array.map (<anonymous>)
at buildArgv (node_modules/@storybook/test-runner/node_modules/jest-cli/build/cli/index.js:188:17)
at Object.run (node_modules/@storybook/test-runner/node_modules/jest-cli/build/cli/index.js:147:18)
at async executeJestPlaywright (node_modules/@storybook/test-runner/dist/test-storybook.js:128:3)
at async main (node_modules/@storybook/test-runner/dist/test-storybook.js:272:3)
```
**Expected behavior**
Specified test file is executed.
> Fix extra args not being passed to jest

- package.json
This PR removes `--no-manager-cache` flag from `yarn start` command.
The following error occurred when I ran `yarn start`.
```
yarn start
yarn run v1.22.19
$ concurrently "yarn build:watch" "yarn storybook -- --no-manager-cache --quiet"
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ storybook dev -p 6006 --no-manager-cache --quiet
$ tsup --watch
[0] CLI Building entry: ./src/index.ts, ./src/setup-page.ts, ./src/test-storybook.ts, ./src/config/jest-playwright.ts, ./src/csf/transformCsf.ts, ./src/playwright/hooks.ts, ./src/playwright/index.ts, ./src/playwright/transformPlaywright.ts, ./src/playwright/transformPlaywrightJson.ts, ./src/util/getCliOptions.ts, …
```
> maintenance: remove no-manager-cache flag in example storybook

- yarn.lock
This commits the result of running [`yarn dedupe`](https://dev.to/arcanis/yarn-2-2-dedupe-faster-lighter-ha5) ([docs](https://yarnpkg.com/cli/dedupe)).
`node_modules` size before vs after:
```
$ du -hs node_modules
1.1G    node_modules
```
```
$ du -hs node_modules
577M    node_modules
```
> chore: dedupe dependency versions in `yarn.lock`

- package.json
This indicates currently working Node.js versions.
Below error on Node.js v10:
```
$ yarn
internal/modules/cjs/loader.js:638
throw err;
^
Error: Cannot find module 'worker_threads'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
at Function.Module._load (internal/modules/cjs/loader.js:562:25)
at Module.require (internal/modules/cjs/loader.js:692:17)
at require (internal/modules/cjs/helpers.js:25:18)
at /app/.yarn/releases/yarn-3.6.3.cjs:423:3061
at Object.<anonymous> (/app/.yarn/releases/yarn-3.6.3.cjs:744:8770)
at Module._compile (internal/modules/cjs/loader.js:778:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```
> chore: set `engines.node` to `>=12.0.0`

- README.md
> Docs: Expand ejected config docs with an example

- .storybook/test-runner.ts
- README.md
- src/playwright/hooks.ts
All information about this is available here: https://github.com/storybookjs/test-runner/issues/50#issuecomment-1755361162
<details>
<summary>📦 Published PR as canary version: <code>0.14.0--canary.361.e0c0bcf.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.14.0--canary.361.e0c0bcf.0
yarn add @storybook/test-runner@0.14.0--canary.361.e0c0bcf.0
```
</details>
> Add waitForPageReady utility

- package.json
This tentatively aligns `node.engines` with that of Jest 29, except without v19.
- #353 
- #348
> BREAKING: Bump minimum Node.js version to ^14.15.0

- MIGRATION.md
- MIGRATION.portable-stories.md
- MIGRATION.test-runner.md
> Add storyshots migration guides

- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .github/workflows/stress-test.yml
- .github/workflows/tests-extended.yml
- .github/workflows/tests.yml
- README.md
- package.json
- src/util/getStorybookMetadata.test.ts
- yarn.lock
<details>
<summary>📦 Published PR as canary version: <code>0.14.2--canary.389.81c8ea1.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.14.2--canary.389.81c8ea1.0
yarn add @storybook/test-runner@0.14.2--canary.389.81c8ea1.0
```
</details>
> Chore: update wait-on and lockfile

- src/test-storybook.ts
> fix: switch `checkStorybook` to use `GET` method

- src/playwright/hooks.ts
The new `tags` option in the `TestRunnerConfig` is currently required and each property is also required. This results in the developer having to include all of it, even when not used.
```js
{
tags: {
include: [],
exclude: [],
skip: [],
},
},
```
This PR makes it optional and does not require all properties, allowing for only used properties to be defined.
```js
{
tags: {
exclude: ['design'],
},
},
```
> fix: Make tags optional in TestRunnerConfig

- .storybook/test-runner.ts
- MIGRATION.test-runner.md
- README.md
- playwright/jest-setup.js
- playwright/test-runner-jest.config.js
- src/playwright/hooks.ts
- src/playwright/transformPlaywright.test.ts
- src/playwright/transformPlaywright.ts
- src/playwright/transformPlaywrightJson.test.ts
- src/test-storybook.ts
- src/typings.d.ts
This PR introduces a change in the test-runner where the hooks previously known as `preRender` and `postRender` now become `preVisit` and `postVisit`.
This is mostly to address concerns regarding confusion from users, who think that the test-runner is related to the rendering of stories. By renaming to "visit", we make it more explicit that the test-runner visits the story, and watches what it does, rather than do many things that will alter the rendering of a story.
There are no breaking changes, it's backwards compatible and the "render" hooks are deprecated and will alert the user to switch to the "visit" hooks.
Additionally, all of the documentation was changed to use Typescript.
<details>
<summary>📦 Published PR as canary version: <code>0.15.2--canary.394.e6df920.0</code></summary> …
> Refactor: Rename "render" hooks to "visit" hooks

- README.md
It took me a while to realize what the difference is between skipped and excluded tags (https://github.com/storybookjs/test-runner/pull/382#issuecomment-1815323026).  This is an attempt to clarify the docs in the README.
> Clarify difference between skipped and excluded tags

- playwright/jest-setup.js
- src/config/jest-playwright.ts
- src/playwright/hooks.ts
- src/playwright/transformPlaywright.test.ts
- src/playwright/transformPlaywright.ts
- src/playwright/transformPlaywrightJson.test.ts
- src/setup-page.ts
Closes #336 
This PR introduces changes to fix a critical bug and handle uncaught page errors, which previously would crash the browser, but now will be provided as proper errors in the specific story which causes it.
> Fix "Browser has been closed" crash on uncaught page errors

- README.md
Closes #275
This PR adds a small subsection to the Troubleshooting section regarding React Native support.
> Docs: Add react native remark to troubleshooting section

- package.json
- yarn.lock
fixes #386
This PR proposes to bump `jest-playwright-preset` package from `v3.0.1` to `v4.0.0` in order to fix the moderate vulnerability stemming Axios reported by Dependabot.
[jest-playwright-preset@v4.0.0 Release note](https://github.com/playwright-community/jest-playwright/releases/tag/v4.0.0)
> Bump `jest-playwright-preset` from `v3.0.1` to `v4.0.0`

- playwright/jest-setup.js
- src/csf/__snapshots__/transformCsf.test.ts.snap
- src/playwright/hooks.ts
- src/playwright/transformPlaywright.test.ts
- src/playwright/transformPlaywright.ts
- src/playwright/transformPlaywrightJson.test.ts
- src/setup-page-script.ts
- src/setup-page.ts
Closes #62 
This PR introduces changes that finally fixes sync issues between failing stories. There are no leaks anymore. Thank god.
<details>
<summary>📦 Published PR as canary version: <code>0.15.3--canary.404.6dbd144.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.15.3--canary.404.6dbd144.0
yarn add @storybook/test-runner@0.15.3--canary.404.6dbd144.0
```
</details>
> Fix sync issues between tests

- src/setup-page-script.ts
> Filter duplicated error messages in browser logs

- .storybook/test-runner.ts
- README.md
- src/playwright/hooks.ts
- src/setup-page-script.ts
- src/setup-page.ts
This PR adds a feature to tweak with logLevels in the test-runner.
As part of this work, the following methods are also collected (in verbose log level): `info, table, dir, debug`
When tests fail and there were browser logs during the rendering of a story, the test-runner provides the logs alongside the error message. The `logLevel` property defines what kind of logs should be displayed:
- **`info` (default):** Shows console logs, warnings, and errors.
- **`warn`:** Shows only warnings and errors.
- **`error`:** Displays only error messages.
- **`verbose`:** Includes all console outputs, including debug information and stack traces.
- **`none`:** Suppresses all log output.
```ts
// .storybook/test-runner.ts
import type { TestRunnerConfig } from '@storybook/test-runner';
const config: …
```
> Introduce logLevel configuration

- src/csf/transformCsf.ts
This PR adds support for the use of ID in stories which we are used for permalinking, e.g.
```ts
export default {
title: 'Components/Notifications/In-page Alerts',
component: InPageAlert,
id: 'in-page-alerts',
}
```
<details>
<summary>📦 Published PR as canary version: <code>0.16.1--canary.419.49762ec.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.16.1--canary.419.49762ec.0
yarn add @storybook/test-runner@0.16.1--canary.419.49762ec.0
```
</details>
> Support stories with meta id for permalinking

- README.md
In issue #394, `postRender` was renamed to `postVisit`, and the use of `postRender` was deprecated. 
However, there were still some parts in the README where `postRender` was being used.
In this PR, `postRender` has been replaced with `postVisit` to avoid using the deprecated function in implementation samples.
> docs: replace postRender(deprecated) with postVisit

- .github/workflows/nightly.yml
Works on https://github.com/storybookjs/storybook/issues/25293
Depends on https://github.com/storybookjs/storybook/pull/25553 getting released by https://github.com/storybookjs/storybook/pull/25546
The `--prerelease` flag has been removed from the `upgrade` command in SB 8.
> Remove --prerelease from sb upgrade CI

- README.md
Closes https://github.com/storybookjs/storybook/issues/23654
This PR adds a remark regarding usage of the test-runner and PnP mode, assisting users to fix issues that might arise
<details>
</details>
> Docs: Add remark regarding pnp support

- src/test-storybook.ts
Closes #[459](https://github.com/storybookjs/test-runner/issues/459)
This PR attempts to fix a Windows compatibility issue when generating coverage. By using node to execute the binary file instead, it should work cross-platform.
<details>
</details>
<details>
<summary>📦 Published PR as canary version: <code>0.18.1--canary.461.8fa90ff.0</code></summary>
<br /> …
> Fix Windows support in coverage generation

- src/playwright/transformPlaywrightJson.ts
Closes https://github.com/storybookjs/test-runner/issues/472
Include support for v5 which is identical to v4 in every meaningful way
Run the test-runner in `index.json` mode against an 8.1.4+ Storybook
> Fix 8.1.4+ support for v5 index.json

- package.json
- yarn.lock
ref https://github.com/storybookjs/test-runner/pull/474
https://github.com/swc-project/swc/issues/8988 was fixed in 1.5.22, so let's unpin @swc/core from 1.5.7. This prevents users from installing an additional version of @swc/core.
Manual testing is not necessary because @swc/core is tested automatically.
<details>
</details>
> Unpin @swc/core from 1.5.7

- src/test-storybook.ts
Closes #479 
<details>
</details>
<details>
<summary>📦 Published PR as canary version: <code>0.18.3--canary.483.3c11018.0</code></summary>
<br />
```bash
npm install @storybook/test-runner@0.18.3--canary.483.3c11018.0
yarn add @storybook/test-runner@0.18.3--canary.483.3c11018.0
```
</details>
> Fix contents of eject functionality

- .storybook/preview.ts
- README.md
- src/csf/transformCsf.ts
- src/playwright/transformPlaywright.test.ts
- src/playwright/transformPlaywright.ts
- src/playwright/transformPlaywrightJson.test.ts
- src/playwright/transformPlaywrightJson.ts
- src/test-storybook.ts
- src/util/getTagOptions.ts
Closes #484
This PR fixes the issue with tag filtering inconsistency between non-index-json mode and index-json mode.
Additionally, it adds a default include filter for stories tagged as `test`. It has backwards compatibility with older indexes such as v3 and v4.
<details>
</details>
<details>
<summary>📦 Published PR as canary version: <code>0.18.3--canary.485.a54e616.0</code></summary>
<br />
:sparkles: …
> Fix: Combine tags correctly when transforming story files

- package.json
- yarn.lock
This should ensure that the `combineTags` helper is available as older versions of the package did not have it.
Closes https://github.com/storybookjs/test-runner/issues/487
<details>
</details>
> fix(deps): upgrade `@storybook/csf` to v0.1.11

- README.md
- src/util/getParsedCliOptions.ts
Closes #328
Unlocks the ability to only rerun failing tests in CI (in my case, CircleCI) instead of having to rerun the entire test suite. Useful when there are flakey tests.
<details>
</details>
> Feature: Add --listTests flag from Jest

- src/setup-page-script.ts
> Fix: Handle RSC errors

- src/setup-page.ts
Closes https://github.com/storybookjs/storybook/issues/30472
Closes https://github.com/storybookjs/storybook/issues/30385
Relates https://github.com/storybookjs/test-runner/issues/68#issuecomment-2669476600
The test-runner used the `storyRendered` event to determine whether a story has finished rendering, including executing `play` functions. In Storybook 8.4, we have introduced a new Storybook lifecycle step called `storyFinished`, which waits for `storyRendered` **and** `afterEach` calls on a story. The `@storybook/addon-a11y` addon for example registers an `afterEach` hook to run axe-based accessibility tests. 
When the `test-runner` was for example set up with `axe-playwright` it happened, that `axe` was running twice. Once from `@storybook/addon-a11y` during the afterEach lifecycle …
> fix: Use StoryFinished event if available

- src/setup-page-script.ts
> Exclude new server component error

- src/test-storybook.ts
Closes #538
Fix the bug where index-json flag is not honored for locally deployed storybooks
I tested this in an internal repo for my org.
<details>
</details>
> Fix --index-json flag not being honored for locally deployed storybooks

- .storybook/preview.ts
- .storybook/test-runner.ts
- README.md
- package.json
- src/setup-page-script.ts
- yarn.lock
Closes #
**Before:**
- Users had to install `axe-playwright` and write code from a recipe with test-runner hooks
- It was easy to miss passing the story context to the a11y report and therefore there would be a mismatch between the addon a11y settings and the a11y test in the test-runner
- Logs weren't attached to the test result
- Logs took a lot of space and were hard to parse
**After:**
- No need for extra dependencies, works out of the box
- Respects the `a11y.test` parameter as [per the docs](https://storybook.js.org/docs/writing-tests/accessibility-testing#configure-accessibility-tests-with-the-test-addon)
- Error logs are attached to the test result
- Logs are formatted and easy to parse
- There is a link to debug directly in the a11y panel
Additionally, there is the `a11y.test: …
> Add out of the box support for a11y tests
